#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PYTHON_BIN="$ROOT_DIR/.venv/bin/python"

if [ ! -x "$PYTHON_BIN" ]; then
  PYTHON_BIN="$(command -v python3 || true)"
fi

if [ -z "${PYTHON_BIN:-}" ]; then
  echo "Python not found. Expected .venv/bin/python or python3."
  exit 1
fi

cd "$ROOT_DIR"

"$PYTHON_BIN" - <<'PY'
import json
from datetime import datetime, timezone
from pathlib import Path

try:
    import yaml
except ImportError:
    raise SystemExit("Missing dependency: pyyaml. Install with: uv add pyyaml")

required = [
    "runtime/objective/objective.yaml",
    "runtime/state/state.json",
    "runtime/state/current_iteration.json",
    "runtime/state/val_loss.json",
    "runtime/knowledge/learned_patterns.md",
    "runtime/knowledge/rejected_ideas.md",
    "runtime/history/timeline.json",
    "runtime/experiments/best.json",
]

missing = [p for p in required if not Path(p).exists()]
if missing:
    raise SystemExit("Missing required Phase B files:\n" + "\n".join(missing))

state_path = Path("runtime/state/state.json")
current_path = Path("runtime/state/current_iteration.json")
timeline_path = Path("runtime/history/timeline.json")

state = json.loads(state_path.read_text(encoding="utf-8"))
current = json.loads(current_path.read_text(encoding="utf-8"))
timeline = json.loads(timeline_path.read_text(encoding="utf-8"))

if state.get("phase") != "B":
    print(f"Phase B skipped. Current phase is {state.get('phase')}.")
    raise SystemExit(0)

objective = yaml.safe_load(Path("runtime/objective/objective.yaml").read_text(encoding="utf-8"))
val_loss = json.loads(Path("runtime/state/val_loss.json").read_text(encoding="utf-8"))
best = json.loads(Path("runtime/experiments/best.json").read_text(encoding="utf-8"))
learned = Path("runtime/knowledge/learned_patterns.md").read_text(encoding="utf-8")
rejected = Path("runtime/knowledge/rejected_ideas.md").read_text(encoding="utf-8")

phase_step = state.get("phase_step", "B1")
now = datetime.now(timezone.utc).isoformat()

if phase_step == "B1":
    next_iteration = int(state.get("iteration", 0)) + 1
    exp_name = f"exp_{next_iteration:04d}_exploration"

    debate_path = Path(f"runtime/debates/{exp_name}.md")
    if debate_path.exists():
        raise SystemExit(f"Debate file already exists and must not be overwritten: {debate_path}")

    current.update({
        "exp_name": exp_name,
        "iteration": next_iteration,
        "objective_summary": objective.get("goal"),
        "candidate_directions": [],
        "deduplicated_directions": [],
        "selected_direction": None,
        "modification_plan": None,
        "code_change_summary": None,
        "local_validation": {
            "status": "not_started",
            "commands": [],
            "passed": False,
            "notes": []
        },
        "remote_training": {
            "status": "not_started",
            "server": None,
            "remote_dir": None,
            "train_command": None,
            "cron_id": None,
            "log_path": None,
            "started_at": None,
            "ended_at": None
        },
        "result": {
            "status": "pending",
            "best_val_loss": None,
            "final_val_loss": None,
            "best_epoch": None,
            "is_new_best": False
        },
        "root_cause_analysis": {
            "status": "not_started",
            "agent_votes": [],
            "verdict": None,
            "summary": None
        },
        "updated_at": now
    })

    current_path.write_text(
        json.dumps(current, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8"
    )

    recent_records = val_loss.get("records", [])[:10]
    best_record = best.get("best")

    constraints_yaml = yaml.safe_dump(objective.get("constraints", {}), sort_keys=False)
    exploration_policy_yaml = yaml.safe_dump(objective.get("exploration_policy", {}), sort_keys=False)
    best_record_json = json.dumps(best_record, indent=2, ensure_ascii=False)
    recent_records_json = json.dumps(recent_records, indent=2, ensure_ascii=False)

    debate_text = f"""# AgentTeam Debate: {exp_name}

## Status

WAITING_FOR_AGENTTEAM

This file is generated by Phase B/B1. Claude/AgentTeam must fill the required sections below, then update `runtime/state/current_iteration.json` and advance the workflow to Phase C/C1.

---

## Experiment Metadata

- Experiment name: `{exp_name}`
- Iteration: {next_iteration}
- Created at: {now}
- Primary metric: `{objective.get("primary_metric", {}).get("name", "val_loss")}`
- Metric mode: `{objective.get("primary_metric", {}).get("mode", "minimize")}`

---

## Objective

{objective.get("goal")}

---

## Constraints

```yaml
{constraints_yaml}
```

---

## Exploration Policy

```yaml
{exploration_policy_yaml}
```

---

## Best Known Experiment

```json
{best_record_json}
```

---

## Recent Validation-Loss Records

```json
{recent_records_json}
```

---

## Learned Patterns

{learned}

---

## Rejected Ideas

{rejected}

---

# AgentTeam Task

Generate candidate architecture modifications for `project/nn-architecture`.

The team must produce:

1. Three candidate directions per role.
2. A historical-overlap review against rejected ideas and previous experiments.
3. A debate over feasibility, expected validation-loss impact, implementation risk, and ablation value.
4. One selected direction.
5. A concrete modification plan.

Do not select a direction that substantially repeats rejected ideas unless there is a new mechanism or diagnostic reason.

---

# Required Output Format

Claude/AgentTeam must fill the following sections.

## Candidate Directions

```json
[]
```

Expected item schema:

```text
{{
  "source": "role-name",
  "title": "short direction name",
  "rationale": "why it may improve val_loss",
  "implementation_hint": "where/how to implement",
  "historical_overlap_risk": "low|medium|high",
  "expected_risk": "low|medium|high"
}}
```

## Deduplicated Directions

```json
[]
```

## Debate Summary

Write the debate summary here.

## Selected Direction

```json
null
```

Expected schema:

```text
{{
  "title": "selected direction",
  "rationale": "why selected",
  "expected_val_loss_effect": "expected effect",
  "risk": "low|medium|high"
}}
```

## Modification Plan

```json
null
```

Expected schema:

```text
{{
  "status": "ready_for_implementation",
  "selected_direction": "selected direction title",
  "implementation_scope": [
    "project/nn-architecture"
  ],
  "files_to_modify": [],
  "local_validation_commands": [
    "python3 -m compileall ."
  ],
  "notes": []
}}
```

---

# Required Runtime Updates After Filling This File

After AgentTeam produces a real plan, update:

```text
runtime/state/current_iteration.json
```

Required fields:

```json
{{
  "candidate_directions": "...",
  "deduplicated_directions": "...",
  "selected_direction": "...",
  "modification_plan": "...",
  "local_validation.commands": "..."
}}
```

Then run:

```bash
./scripts/set_phase.sh C C1
```
"""

    debate_path.write_text(debate_text, encoding="utf-8")

    timeline.setdefault("events", []).append({
        "time": now,
        "iteration": next_iteration,
        "exp_name": exp_name,
        "event_type": "phase_b_agentteam_prompt_created",
        "phase": "B",
        "summary": "Phase B created an AgentTeam debate prompt and is waiting for a real modification plan.",
        "best_val_loss": best_record.get("best_val_loss") if isinstance(best_record, dict) else None,
        "is_new_best": False
    })
    timeline_path.write_text(
        json.dumps(timeline, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8"
    )

    state.update({
        "workflow_status": "running",
        "phase": "B",
        "phase_step": "B2",
        "iteration": next_iteration,
        "current_exp_name": exp_name,
        "next_phase": "B",
        "blocked": False,
        "block_reason": None,
        "updated_at": now
    })
    state_path.write_text(
        json.dumps(state, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8"
    )

    print("== Phase B: Exploration Direction Generation ==")
    print(f"exp_name: {exp_name}")
    print(f"debate_path: {debate_path}")
    print("Phase B/B1 completed. Waiting for AgentTeam output at Phase B/B2.")
    raise SystemExit(0)

if phase_step == "B2":
    exp_name = current.get("exp_name")
    debate_path = Path(f"runtime/debates/{exp_name}.md") if exp_name else None

    print("== Phase B: Waiting for AgentTeam Output ==")
    print(f"exp_name: {exp_name}")
    print(f"debate_path: {debate_path}")

    if not exp_name or not debate_path or not debate_path.exists():
        reason = "Phase B/B2 requires existing debate file and current_iteration.exp_name"
        state.update({
            "workflow_status": "blocked",
            "phase": "BLOCKED",
            "phase_step": "BLOCKED",
            "blocked": True,
            "block_reason": reason,
            "updated_at": now,
        })
        state_path.write_text(json.dumps(state, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        raise SystemExit(reason)

    if not current.get("modification_plan") or not current.get("selected_direction"):
        print("AgentTeam output is not ready.")
        print("Fill the debate file and update current_iteration.json, then run:")
        print("./scripts/set_phase.sh C C1")
        raise SystemExit(0)

    state.update({
        "workflow_status": "running",
        "phase": "C",
        "phase_step": "C1",
        "next_phase": "C",
        "blocked": False,
        "block_reason": None,
        "updated_at": now
    })

    timeline.setdefault("events", []).append({
        "time": now,
        "iteration": state.get("iteration", current.get("iteration")),
        "exp_name": exp_name,
        "event_type": "phase_b_completed",
        "phase": "B",
        "summary": "AgentTeam output detected. Workflow advanced to Phase C.",
        "best_val_loss": best.get("best", {}).get("best_val_loss") if best.get("best") else None,
        "is_new_best": False
    })

    timeline_path.write_text(json.dumps(timeline, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    state_path.write_text(json.dumps(state, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    print("Phase B/B2 completed. Advanced to Phase C/C1.")
    raise SystemExit(0)

reason = f"Unsupported Phase B step: {phase_step}"
state.update({
    "workflow_status": "blocked",
    "phase": "BLOCKED",
    "phase_step": "BLOCKED",
    "blocked": True,
    "block_reason": reason,
    "updated_at": now,
})
state_path.write_text(json.dumps(state, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
raise SystemExit(reason)
PY
