#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PYTHON_BIN="$ROOT_DIR/.venv/bin/python"

if [ ! -x "$PYTHON_BIN" ]; then
  PYTHON_BIN="$(command -v python3 || true)"
fi

if [ -z "${PYTHON_BIN:-}" ]; then
  echo "Python not found. Expected .venv/bin/python or python3."
  exit 1
fi

cd "$ROOT_DIR"

"$PYTHON_BIN" - <<'PY'
import json
from datetime import datetime, timezone
from pathlib import Path

try:
    import yaml
except ImportError:
    raise SystemExit("Missing dependency: pyyaml. Install with: uv add pyyaml")

required = [
    "runtime/objective/objective.yaml",
    "runtime/state/state.json",
    "runtime/state/current_iteration.json",
    "runtime/state/val_loss.json",
    "runtime/knowledge/learned_patterns.md",
    "runtime/knowledge/rejected_ideas.md",
    "runtime/history/timeline.json",
    "runtime/experiments/best.json",
]

missing = [p for p in required if not Path(p).exists()]
if missing:
    raise SystemExit("Missing required Phase B files:\n" + "\n".join(missing))

state_path = Path("runtime/state/state.json")
current_path = Path("runtime/state/current_iteration.json")
timeline_path = Path("runtime/history/timeline.json")

state = json.loads(state_path.read_text(encoding="utf-8"))
current = json.loads(current_path.read_text(encoding="utf-8"))
timeline = json.loads(timeline_path.read_text(encoding="utf-8"))

if state.get("phase") != "B":
    print(f"Phase B skipped. Current phase is {state.get('phase')}.")
    raise SystemExit(0)

objective = yaml.safe_load(Path("runtime/objective/objective.yaml").read_text(encoding="utf-8"))
val_loss = json.loads(Path("runtime/state/val_loss.json").read_text(encoding="utf-8"))
best = json.loads(Path("runtime/experiments/best.json").read_text(encoding="utf-8"))
learned = Path("runtime/knowledge/learned_patterns.md").read_text(encoding="utf-8")
rejected = Path("runtime/knowledge/rejected_ideas.md").read_text(encoding="utf-8")

next_iteration = int(state.get("iteration", 0)) + 1
exp_name = f"exp_{next_iteration:04d}_exploration"

candidate_directions = [
    {
        "source": "architect",
        "title": "Architecture-level modification placeholder",
        "rationale": "To be replaced by AgentTeam debate output.",
        "historical_overlap_risk": "unknown"
    },
    {
        "source": "optimizer",
        "title": "Efficiency-aware modification placeholder",
        "rationale": "To be replaced by AgentTeam debate output.",
        "historical_overlap_risk": "unknown"
    },
    {
        "source": "skeptic",
        "title": "Minimal-change baseline control placeholder",
        "rationale": "To be replaced by AgentTeam debate output.",
        "historical_overlap_risk": "unknown"
    }
]

deduplicated_directions = candidate_directions

selected_direction = deduplicated_directions[0]

modification_plan = {
    "status": "draft",
    "selected_direction": selected_direction["title"],
    "implementation_scope": [
        "project/nn-architecture"
    ],
    "local_validation_commands": [
        "python -m compileall ."
    ],
    "notes": [
        "This is a placeholder plan. Replace it with AgentTeam-generated plan before real implementation."
    ]
}

debate_path = Path(f"runtime/debates/{exp_name}.md")
debate_path.parent.mkdir(parents=True, exist_ok=True)

if debate_path.exists():
    raise SystemExit(f"Debate file already exists and must not be overwritten: {debate_path}")

now = datetime.now(timezone.utc).isoformat()

debate_text = f"""# AgentTeam Debate: {exp_name}

## Created At

{now}

## Objective

{objective.get("goal")}

## Historical Context Summary

- Existing val_loss records: {len(val_loss.get("records", []))}
- Has best experiment: {best.get("best") is not None}
- Learned patterns length: {len(learned)} characters
- Rejected ideas length: {len(rejected)} characters

## Candidate Directions

{json.dumps(candidate_directions, indent=2, ensure_ascii=False)}

## Deduplicated Directions

{json.dumps(deduplicated_directions, indent=2, ensure_ascii=False)}

## Selected Direction

{json.dumps(selected_direction, indent=2, ensure_ascii=False)}

## Modification Plan

{json.dumps(modification_plan, indent=2, ensure_ascii=False)}

## AgentTeam Notes

This file is currently generated by the Phase B scaffold.

In the full workflow, this section should contain:

- Per-agent candidate directions
- Historical overlap review
- Debate transcript
- Skeptic objections
- Lead decision
- Final implementation plan
"""

debate_path.write_text(debate_text, encoding="utf-8")

current.update({
    "exp_name": exp_name,
    "iteration": next_iteration,
    "objective_summary": objective.get("goal"),
    "candidate_directions": candidate_directions,
    "deduplicated_directions": deduplicated_directions,
    "selected_direction": selected_direction["title"],
    "modification_plan": json.dumps(modification_plan, indent=2, ensure_ascii=False),
    "code_change_summary": None,
    "local_validation": {
        "status": "planned",
        "commands": modification_plan["local_validation_commands"],
        "passed": False,
        "notes": []
    },
    "remote_training": {
        "status": "not_started",
        "server": None,
        "remote_dir": None,
        "train_command": None,
        "cron_id": None,
        "log_path": None,
        "started_at": None,
        "ended_at": None
    },
    "result": {
        "status": "pending",
        "best_val_loss": None,
        "final_val_loss": None,
        "best_epoch": None,
        "is_new_best": False
    },
    "root_cause_analysis": {
        "status": "not_started",
        "agent_votes": [],
        "verdict": None,
        "summary": None
    },
    "updated_at": now
})

current_path.write_text(
    json.dumps(current, indent=2, ensure_ascii=False) + "\n",
    encoding="utf-8"
)

timeline.setdefault("events", []).append({
    "time": now,
    "iteration": next_iteration,
    "exp_name": exp_name,
    "event_type": "phase_b_completed",
    "phase": "B",
    "summary": "Candidate directions were generated and a placeholder modification plan was created.",
    "best_val_loss": best.get("best", {}).get("best_val_loss") if best.get("best") else None,
    "is_new_best": False
})
timeline_path.write_text(
    json.dumps(timeline, indent=2, ensure_ascii=False) + "\n",
    encoding="utf-8"
)

state.update({
    "phase": "C",
    "phase_step": "C1",
    "iteration": next_iteration,
    "current_exp_name": exp_name,
    "next_phase": "C",
    "updated_at": now
})

state_path.write_text(
    json.dumps(state, indent=2, ensure_ascii=False) + "\n",
    encoding="utf-8"
)

print("== Phase B: Exploration Direction Generation ==")
print(f"exp_name: {exp_name}")
print(f"debate_path: {debate_path}")
print("Phase B completed. Advanced to Phase C/C1.")
PY